install.packages("palmerpenguins")
install.packages("here")
require(palmerpenguins)
require(here)
library("palmerpenguins")
class(penguins)
penguins = data.frame(penguins)
mean(penguins$body_mass_g)
head(penguins)
?mean
mean(penguins$body_mass_g, na.rm=TRUE)
summary(penguins)
plot(penguins)
plot(penguins$body_mass_g)
plot(penguins$body_mass_g, penguins$flipper_length_mm)
boxplot(penguins$bill_depth_mm)
boxplot(bill_depth_mm ~ sex, data = penguins)
par(mfrow = c(1, 2))
boxplot(penguins$bill_depth_mm)
boxplot(bill_depth_mm ~ sex, data = penguins)
coplot(body_mass_g ~ bill_depth_mm | sex, data = penguins)
coplot(body_mass_g ~ bill_depth_mm | year, data = penguins,
       title(main="E. Baylor Data Set 2")
require(here)
png(filename = here("basic_histogram.png"), width = 800, height = 600)
hist(penguins$body_mass_g)
dev.off()
